//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class department
    {
        public int ID { get; set; }
        [Display(Name = "Department Name")]
        [Required]
        public string DepName { get; set; }
        public Nullable<int> Manager { get; set; }
    }
}
